### ISSUE TITLE
Align Header and Table to center

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Leaderboard#1]
Align the Header and table to center using css rules
Follow the rules given below

- Fork and clone the repo
- Create a css file `style.css` in the root directory
- Make the neccessary changes in the css and html files.
- After commiting the changes create a pull repository following the PR template

**Comment by PiyushGG18** [comment]
Claim, I want to work on this issue

**Comment by KBVijayVarma** [comment]
Claim

**Comment by bhumi-cka** [comment]
Claim

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by hargunkaur286** [comment]
Claim

**Comment by shiva177** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by sushantk1274** [comment]
claim, i want to work on this issue

**Comment by Kali-Decoder** [comment]
Please Assign Me

**Comment by hackerishan-123** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
Claim
