### ISSUE TITLE
Basic Layout

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Leaderboard#14]
Follow the design given in the [design file](https://www.figma.com/file/iMrQnNeRhFrzt8Z7rvpvKb/Leaderboard?node-id=0%3A1) and do the following:
 - Attach icons of Opencode'22 and Geekhaven
 - Display the headings of the page

*Note: The page should be completely responsive and don't forget to pull the changes before making a PR.*

**Comment by abhinavs1920** [comment]
Claim

**Comment by JahnaviGadde** [comment]
claim
