### ISSUE TITLE
Display Content from dummy data

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Leaderboard#6]
Create a function `displayData()` in the script tag in `index.html` to display the leaderboard data in the table. Use the file `dummyData.json` as data-input and pass the data to `addToTable()`. 
You should comment the getData() function where it is being called, and call the `displayData()` function instead.

**Comment by vedant-z** [comment]
Claim

**Comment by akshatsgh** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim

**Comment by vedant-z** [comment]
No sir

**Comment by vedant-z** [comment]
![image](https://user-images.githubusercontent.com/93431609/208438362-36caa54e-b580-4e08-a132-2025cc6059e4.png)

JWT issue has been solved already and my PR is merged as well. The issue is not closed by the owner yet.

**Comment by Kali-Decoder** [comment]
Rule is one issue is assign at a particular time in a repo ??? So Why three ??

**Comment by vedant-z** [comment]
Those three issues are from diffferent repo @Kali-Decoder

**Comment by Siddhant-Agarwal4583** [comment]
Claim

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim

**Comment by aknsal** [comment]
Closing this issue as the backend api is working and we do not need the dummyData.
